spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dh-caixa-test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    properties.hibernate.format_sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true # modifica o comportamento padrão do Spring Boot e preenche os dados após o esquema ser gerado pelo Hibernate
  h2:
    console:
      enabled: true
      path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false

message: Caixa DH ambiente de TEST
server:
  port: ${PORT_DH_CAIXA:8080}
moeda: Real
notas: 10,20,50