spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/dh-operacoes-prod
    username: ${APP_USERNAME_DB}
    password: ${APP_PASSWORD_DB}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    format_sql: true
    show-sql: true

message: Operações DH ambiente de PROD
server:
  port: ${PORT_DH_CAIXA:8080}
moeda: Real
notas: 10,20,50